/**
 * BIDS Data — Module 7: The Missing Piece
 * Shows what events.tsv is missing (prediction choice, response rating),
 * introduces learn_behavioral.csv, and explains the merge.
 */

import Callout from '@src/components/Callout'
import TryCommand from '@src/components/TryCommand'

export default function PredictionChoice(): React.JSX.Element {
  return (
    <div className="animate-fade-up">
      {/* Header */}
      <div className="mb-8">
        <div className="flex items-center gap-2 mb-3">
          <span className="text-xs font-bold text-[var(--color-accent-bright)] uppercase tracking-[0.08em]">
            Your Data
          </span>
          <span className="text-[var(--color-text-dim)]">&middot;</span>
          <span className="text-xs text-[var(--color-text-muted)]">Module 7 of 8</span>
        </div>
        <h1 className="text-3xl font-bold font-[var(--font-heading)] tracking-tight text-[var(--color-text-primary)]">
          The Missing Piece
        </h1>
        <p className="text-[var(--color-text-secondary)] mt-3 text-lg leading-relaxed">
          The events files tell us <em>when</em> things happened, but not <em>what the subject
          chose</em>. There&rsquo;s a second data source we need.
        </p>
      </div>

      <div className="prose-container">
        {/* ── THE GAP ─────────────────────────────────────── */}
        <h2>What events.tsv Doesn&rsquo;t Tell Us</h2>
        <p>
          Look at a prediction event in events.tsv:
        </p>
        <pre className="code-block"><code>{`onset    duration  event         trial  run  ...
14.0     2.0       Mean_60_pred  3      1    ...`}</code></pre>
        <p>
          We know <em>when</em> the subject made a prediction for the Mean-60% peer (14.0s into
          run 1), and how long it lasted (2.0s). But we don&rsquo;t know the most important thing:
        </p>

        <Callout variant="definition">
          <strong>Did the subject predict &ldquo;nice&rdquo; or &ldquo;mean&rdquo;?</strong> The
          events.tsv file only records that a prediction happened for a given peer &mdash; not
          what the subject actually chose. Without this, we can&rsquo;t model prediction-by-choice
          in the GLM.
        </Callout>

        <p>
          Similarly, response events (<code className="code-inline">Mean_60_rsp</code>) don&rsquo;t
          encode the subject&rsquo;s rating (1&ndash;4). And when subjects miss a prediction entirely,
          the feedback gets labeled <code className="code-inline">nopred_fdbk</code> instead of the
          correct condition &mdash; we lose track of what feedback was actually shown.
        </p>

        {/* ── THE BEHAVIORAL CSV ──────────────────────────── */}
        <h2>The Behavioral CSV</h2>
        <p>
          All of this information lives in a separate file: <strong>learn_behavioral.csv</strong>.
          This file was generated by the task software and contains one row per trial per subject:
        </p>

        <TryCommand
          command="head -5 /data/projects/STUDIES/LEARN/fMRI/RSA-learn/analysis/learn_behavioral.csv"
          execute={true}
          description="Preview the behavioral CSV. Note the columns."
        />

        <div className="my-6 rounded-lg border border-[var(--color-border)] bg-[var(--color-bg-secondary)] p-5">
          <div className="text-[var(--color-accent-bright)] font-bold mb-3">Key Columns</div>
          <div className="space-y-2 text-sm text-[var(--color-text-secondary)]">
            <div><code className="code-inline">s</code> &mdash; Subject ID (e.g., <code className="code-inline">sub-958</code>)</div>
            <div><code className="code-inline">r</code> &mdash; Run number (1&ndash;4)</div>
            <div><code className="code-inline">trial</code> &mdash; Trial number (1&ndash;32 per run)</div>
            <div><code className="code-inline">Reputation</code> &mdash; Peer type (Mean60, Mean80, Nice60, Nice80)</div>
            <div><code className="code-inline">Prediction</code> &mdash; Subject&rsquo;s choice: <strong>1 = nice</strong>, <strong>0 = mean</strong>, <strong>NA = missed</strong></div>
            <div><code className="code-inline">Response</code> &mdash; Rating 1&ndash;4, or NA if missed</div>
            <div><code className="code-inline">fdk_val</code> &mdash; Feedback valence: 1 = nice, 0 = mean</div>
          </div>
        </div>

        <p>
          With 32 trials per run, 4 runs, and 38 subjects, this file has about 6,650 rows
          covering every trial in the experiment.
        </p>

        {/* ── THE JOIN ────────────────────────────────────── */}
        <h2>Joining the Two Files</h2>
        <p>
          We can match rows between events.tsv and the behavioral CSV using three keys:
          <strong> subject + run + trial</strong>. There&rsquo;s one wrinkle:
        </p>

        <div className="my-4 rounded border border-[var(--color-border-dim)] bg-[var(--color-bg-secondary)] p-4">
          <div className="text-[var(--color-accent-bright)] font-bold">ID Mismatch</div>
          <p className="mt-1 text-sm text-[var(--color-text-secondary)]">
            The behavioral CSV uses <code className="code-inline">sub-958</code> while BIDS uses{' '}
            <code className="code-inline">sub-LEARN958</code>. Our enrichment script adds the
            &ldquo;LEARN&rdquo; prefix automatically.
          </p>
        </div>

        <p>
          Once joined, we can take a bare prediction event like <code className="code-inline">Mean_60_pred</code>{' '}
          and enrich it to <code className="code-inline">Mean_60_pred_nice</code> or{' '}
          <code className="code-inline">Mean_60_pred_mean</code> based on what the subject actually chose.
        </p>

        {/* ── WHAT ENRICHMENT DOES ────────────────────────── */}
        <h2>What the Enrichment Script Does</h2>
        <p>
          We wrote a Python script (<code className="code-inline">enrich_events.py</code>) that
          does three things in one pass:
        </p>
        <ol>
          <li>
            <strong>Fixes nopred_fdbk:</strong> When subjects missed a prediction, the feedback
            was labeled <code className="code-inline">nopred_fdbk</code> instead of the correct
            condition (like <code className="code-inline">Mean_60_fdkm</code>). The script uses a
            majority-vote across all subjects to recover the correct label for each trial position.
          </li>
          <li>
            <strong>Enriches predictions:</strong> Adds <code className="code-inline">_nice</code>{' '}
            or <code className="code-inline">_mean</code> to prediction events based on the
            subject&rsquo;s actual choice from the behavioral CSV.
          </li>
          <li>
            <strong>Passes everything else through:</strong> Feedback, response, anticipation, and
            all other events are copied unchanged.
          </li>
        </ol>

        <p>
          The result is written to a new directory &mdash;{' '}
          <code className="code-inline">events_enriched/</code> &mdash; which becomes the
          &ldquo;ground truth&rdquo; source for all downstream steps (timing files, GLM).
        </p>

        {/* ── NEW EVENT LABELS ────────────────────────────── */}
        <h2>New Event Labels</h2>
        <div className="my-6 rounded-lg border border-[var(--color-border)] bg-[var(--color-bg-secondary)] p-5">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
            <div>
              <div className="text-[var(--color-accent-bright)] font-bold mb-2">
                Enriched Prediction Events
              </div>
              <div className="font-mono text-xs text-[var(--color-text-secondary)] space-y-0.5">
                <div>Mean_60_pred_nice &nbsp;<span className="text-[var(--color-text-dim)]"># predicted nice</span></div>
                <div>Mean_60_pred_mean &nbsp;<span className="text-[var(--color-text-dim)]"># predicted mean</span></div>
                <div>Mean80_pred_nice</div>
                <div>Mean80_pred_mean</div>
                <div>Nice_60_pred_nice</div>
                <div>Nice_60_pred_mean</div>
                <div>Nice80_pred_nice</div>
                <div>Nice80_pred_mean</div>
              </div>
            </div>
            <div>
              <div className="text-[var(--color-accent-bright)] font-bold mb-2">
                Unchanged Events
              </div>
              <div className="font-mono text-xs text-[var(--color-text-secondary)] space-y-0.5">
                <div>Mean_60_fdkm, Mean_60_fdkn &nbsp;<span className="text-[var(--color-text-dim)]"># feedback</span></div>
                <div>Mean_60_rsp &nbsp;<span className="text-[var(--color-text-dim)]"># response</span></div>
                <div>isi &nbsp;<span className="text-[var(--color-text-dim)]"># anticipation</span></div>
                <div>no_pred &nbsp;<span className="text-[var(--color-text-dim)]"># missed prediction</span></div>
                <div>no_resp &nbsp;<span className="text-[var(--color-text-dim)]"># missed response</span></div>
              </div>
            </div>
          </div>
        </div>

        <Callout variant="learn">
          <strong>Why this matters for the GLM:</strong> With enriched events, we can model
          prediction-by-choice as separate regressors (e.g., &ldquo;predicting nice for a mean
          peer&rdquo; vs &ldquo;predicting mean for a mean peer&rdquo;). This lets us ask whether
          the brain represents the act of predicting differently depending on what the subject
          expects &mdash; a question we couldn&rsquo;t ask with the raw events files alone.
        </Callout>
      </div>
    </div>
  )
}
