#!/bin/tcsh

#######################################################
# SCRIPT SUMMARY
#######################################################
# RSA‑learn RUN‑WISE AFNI proc runner
#
# Mirrors style of RunAFNIProc_LEARN.sh and runs the
# proc scripts generated by LEARN_ap_Full_RSA_runwise.sh
#
# IMPORTANT:
#   This script executes afni_proc outputs (tcsh -xef)
#   and writes logs into RSA‑learn/logs.
#
# Author: RSA‑learn adaptation
# Date: 2026‑02‑08

############################################################################################
# GENERAL SETUP
############################################################################################

######################################################
# SPECIFY YOUR LOCATIONS AND SUBJECTS
######################################################

# **CHANGE ME**: Specify subject ID numbers in a single row.
# Example: set subjects = ( 1055 )
set subjects = ( 1055 )

# **CHECK ME**: Top‑level study directory
set topdir = /data/projects/STUDIES/LEARN/fMRI

# RSA‑learn output root (where proc scripts live)
set results = $topdir/RSA-learn/derivatives/afni/IndvlLvlAnalyses

# RSA‑learn logs
set logdir = $topdir/RSA-learn/logs
mkdir -p $logdir

############################################################################################
# RUN PROC SCRIPTS
############################################################################################

foreach subj ( $subjects )

    echo "[RSA‑learn] Running subject $subj"

    set proc_script = $results/$subj/proc.$subj.LEARN_RSA_runwise

    if ( ! -e $proc_script ) then
        echo "[RSA‑learn] MISSING: $proc_script"
        echo "[RSA‑learn] Did you run LEARN_ap_Full_RSA_runwise.sh first?"
        continue
    endif

    tcsh -xef $proc_script |& tee $logdir/output.proc.$subj.LEARN_RSA_runwise

end
